### ISSUE TITLE
yarn compile failed

### ISSUE THREAD

**Issue by DreamXzxy** [AztecProtocol/aztec-ganache-starter-kit#32] opened 2020-02-04 03:21 UTC
![image](https://user-images.githubusercontent.com/17998878/73711350-83542e80-4741-11ea-9819-0a1cbd9e3771.png)

**Comment by thomas-waite** [comment] 2020-02-04 16:58
Hi @DreamXzxy , thanks for posting. I can't reproduce this locally - could you try removing your `node_modules` and `build` folder and then re-run 1) `yarn install`, followed by 2) `yarn compile`.

**Comment by thomas-waite** [comment] 2020-02-12 10:58
Hope the above worked for you @DreamXzxy . I'm going to close this issue now as I believe the starter kit is working properly, but feel free to reach out if you have problems

**Closed by thomas-waite** 2020-02-12 10:58 UTC
