### ISSUE TITLE
VM Exception while processing transaction: revert SafeMath: subtraction overflow -- Reason given: SafeMath: subtraction overflow.

### ISSUE THREAD

**Issue by SinTan1071** [AztecProtocol/aztec-ganache-starter-kit#5] opened 2019-11-18 06:37 UTC
Well, I want to use ZkAsset which linked to TestERC20, and I rewrite "demo.js" like this :
```javascript
...
    let aceContract;
    let privatePaymentContract;

    beforeEach(async () => {
        aceContract = await ACE.deployed();
        privatePaymentContract = await ZkAsset.deployed();
        // privatePaymentContract = await ZkAssetMintable.deployed();
    });
...
      console.log('Bob wants to transfer his 100 ERC20 tokens into AZTEC notes');
      const newCounterNote = await aztec.note.create(bob.publicKey, 100);
      const sender = accounts[0];
      const transferAmount = 100;
      const transferPublicValue = -transferAmount;

      const transferProof = new JoinSplitProof(
          // [zeroMintCounterNote],
          [],
          [newCounterNote],
          sender,
          transferPublicValue,
          sender
      );
      const transferProofData = transferProof.encodeABI(privatePaymentContract.address);
      const transferProofSignatures = transferProof.constructSignatures(
          privatePaymentContract.address,
          []
      );

      await aceContract.methods["publicApprove(address,bytes32,uint256)"](
          privatePaymentContract.address,
          transferProof.hash,
          transferAmount,
          {
              from: accounts[0]
          });
      await privatePaymentContract.methods["confidentialTransfer(bytes,bytes)"](
          transferProofData,
          transferProofSignatures,
          {
              from: accounts[0]
          });
      console.log('Bob successfully transfer 100 ERC20 tokens');
```
The method "confidentialTransfer" return an error:
```shell
Error: Returned error: VM Exception while processing transaction: revert SafeMath: subtraction overflow -- Reason given: SafeMath: subtraction overflow.
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at Object.confidentialTransfer(bytes,bytes) (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:170:1)
      at _callee3$ (test/demo.js:203:13)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
Did I use the protocol correctly? How should I do? Would you kindly help me?

**Comment by thomas-waite** [comment] 2019-11-18 18:48
Hey @SinTan1071 , thanks for reaching out; I'm taking a look at this now

**Comment by thomas-waite** [comment] 2019-11-18 20:26
I believe the problem is that the balance of `publicOwner` (the `sender` in your example above) is 0. As a result, when `confidentialTransfer()` is called - the contracts are attempting to transfer 100 tokens from a balance of 0, resulting in a `safeMath` subtraction overflow.

In the adapted script, you are constructing a `JoinSplit` proof to convert 100 ERC20 tokens into zero-knowledge AZTEC notes. These tokens are being taken from the balance of `publicOwner` - `publicOwner` is the 5th input to the `new JoinSplit()` method call, defined as `sender` (itself equal to `accounts[0]`) in your script.

`Truffle` will initialise all `accounts` with a balance of 0 tokens first - so you'll need to create the `TestERC20` instance and mint some tokens to `accounts[0]` with `TestERC20.giveMeTokens()`. You'll then need to `approve()` ACE to spend these tokens. 

We do something along these lines (albeit with a slightly different `ERC20Mintable` contract here (lines 56 - 72): https://github.com/AztecProtocol/AZTEC/blob/develop/packages/protocol/test/ERC1724/ZkAsset.js 

Let me know if that solves it and if you have any more questions! Would be happy to help make this clearer if you have any ideas how.

**Comment by thomas-waite** [comment] 2019-11-18 20:29
Here's a link to our discord server too: https://discord.gg/gewvFqg 

Happy to chat further there if it's helpful

**Comment by SinTan1071** [comment] 2019-11-19 03:13
Thanks for your answer, at the first time, I'm pretty sure I mint some tokens to the `sender`, but when I checked my code again, it turns out the tokens have minted to a different account, my bad. Thanks again.

**Comment by SinTan1071** [comment] 2019-11-19 07:19
@thomas-waite This is awkward, this time I believe the TestERC20 token balance of the sender's account is non-zero, but I still got the same error:
```javascript
......

const ACE = artifacts.require('./ACE.sol');
const TestERC20 = artifacts.require('./TestERC20.sol');
const ZkAsset = artifacts.require('./ZkAsset.sol');
......

  let aceContract;
  let testERC20Contract;
  let privatePaymentContract;

  beforeEach(async () => {
    aceContract = await ACE.deployed();
    testERC20Contract = await TestERC20.deployed();
    privatePaymentContract = await ZkAsset.deployed();
  });
......

    console.log('Bob wants to transfer his 100 ERC20 tokens into AZTEC notes');
    const newCounterNote = await aztec.note.create(bob.publicKey, 100);
    const sender = accounts[0];
    const transferAmount = 100;
    const transferPublicValue = -transferAmount;

    await testERC20Contract.giveMeTokens(accounts[0], 233333333333, { from: accounts[0] });
    await testERC20Contract.balanceOf(accounts[0], { from: accounts[0] }).then(res=>{console.log("Bob's testERC20 token balance ", res)});

    const transferProof = new JoinSplitProof(
        [],
        [newCounterNote],
        sender,
        transferPublicValue,
        sender
    );
   
    const transferProofData = transferProof.encodeABI(privatePaymentContract.address);
    const transferProofSignatures = transferProof.constructSignatures(
        privatePaymentContract.address,
        []
    );

    await aceContract.methods["publicApprove(address,bytes32,uint256)"](
        privatePaymentContract.address,
        transferProof.hash,
        transferAmount,
        {
          from: accounts[0]
        });
    await privatePaymentContract.methods["confidentialTransfer(uint24,bytes,bytes)"](
        JOIN_SPLIT_PROOF,
        transferProofData,
        transferProofSignatures,
        {
          from: accounts[0]
        });
    console.log('Bob successfully transfer 100 ERC20 tokens');

......

```

**Comment by thomas-waite** [comment] 2019-11-19 11:29
Hey no worries, you also just need to approve the `aceContract` to be able to spend those minted tokens. 

The `safeMath` error is being thrown now, I believe, because the approval balance is 0. I've copied your script over locally and if you add the following line in:
```
    await testERC20Contract.approve(aceContract.address, 233333333333);
```

then the test passes. Thanks for flagging this - I'll have a think about how we can make these errors a bit more informative on our side

**Comment by SinTan1071** [comment] 2019-11-20 06:18
@thomas-waite That works!!! Thank you so much, another question for `Sally`, I've noticed that when I try to convert Sally's 25 AZTEC notes back into TestERC20 tokens, there is no need to use the `aceContract.methods["publicApprove(address,bytes32,uint256)"]`, I wonder why.

**Comment by thomas-waite** [comment] 2019-11-20 11:50
The `aceContract.publicApprove()` method is used in cases where tokens are being transferred to the `ACE` contract. 

It's purpose is to keep track of how many tokens the `publicOwner`, for a particular proof, is granting  `ACE` the permission to transfer from their account to `ACE` - i.e. it is necessary when converting tokens to AZTEC notes. 

This is not required when going the other way and converting notes into tokens, because in this case tokens will be being transferred from the `ACE` account to the `publicOwner` instead. 

I've dropped you a message on Discord where we can continue to discuss AZTEC and any implementation questions you may have! 

In the meantime I'm going to close this Github issue as the repo appears to be functioning as intended. Thanks again :)

**Closed by thomas-waite** 2019-11-20 11:50 UTC

**Comment by SinTan1071** [comment] 2019-11-21 01:29
Appreciate it, I'll keep on following your updates and try to learn the protocol better.

**Comment by SinTan1071** [comment] 2019-12-02 08:47
@thomas-waite Hi, thomas, remember me? I wonder if you guys have any magical way to transfer the ERC-721 token confidentially, and with AZTEC protocol, we can protect the privacy of our transactions data, but how can we protect the privacy of our transactions identities?

**Comment by thomas-waite** [comment] 2019-12-03 10:48
hey @SinTan1071 , I've dropped you a message on discord where we can talk in detail :)

**Comment by SinTan1071** [comment] 2019-12-04 02:57
@thomas-waite 😂 Unfortunately, I can't access the discord page for a long time...

**Comment by SinTan1071** [comment] 2019-12-04 03:05
@thomas-waite How about keybase? I can use that 🤔
