### ISSUE TITLE
Error when compiling the aztec contracts

### ISSUE THREAD

**Issue by pegartillo95** [AztecProtocol/aztec-ganache-starter-kit#8] opened 2019-12-18 11:00 UTC
I'm getting this error when executing "yarn compile" on this starter kit.
Previously I have executed "yarn install" and "yarn start" to bring up the ganache network.

yarn compile
yarn run v1.19.1
$ truffle compile --all

Compiling your contracts...
-------------------------------------
Error: TypeError: soljson.Pointer_stringify is not a function
    at Object.compile (/Users/macblockchain1/Documents/aztec-ganache-starter-kit/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:72:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.4 (core: 5.1.4)
Node v10.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

As you can see I'm using node version 10.17.0. I have also tried with version 12.12.0, 12.14.0 and 8.17.0. And I get the same error.

**Comment by thomas-waite** [comment] 2019-12-18 11:04
Hey @pegartillo95 thanks for raising the issue. I'll take a look at this today and get back to you :)

**Comment by thomas-waite** [comment] 2019-12-18 20:54
Thanks again for flagging this @pegartillo95 . I believe I've now pushed a fix - if you can pull from `master`, try compiling the contracts again and then let me know if it works for you that'd be great. 

I believe the problem was caused by the `truffle-config` not specifying the version of the `solc` compiler to use (it previously set it as `>=0.5.0 <0.7.0`) . 

This means that it's possible a compiler version could be used which is incompatible with the AZTEC contracts, causing the compilation to fail. I've now specified it as `0.5.7` - this is what we currently use in the main AZTEC repo.

This fixes the problem locally for me and on circleci - let me know if it works for you

**Comment by pegartillo95** [comment] 2019-12-19 08:27
Hello Thomas:
I have pull your last changes and now it does work perfectly.
I would like to have some conversations over mail if possible because I'm now trying to work with Aztec and I do have some ideas and doubts that I would like to discuss with you.
Should I write to the mail you have here at GitHub?

**Comment by thomas-waite** [comment] 2019-12-19 10:53
Great to hear that the change fixed the problem, and also that you're working with AZTEC. I'd be very happy to chat and answer any questions you may have. 

My email is: tom.waite@aztecprotocol.com ; or if you prefer discord then this is a link to our server where we can talk further: https://discord.gg/bbGHmz

**Closed** 2019-12-19 11:38 UTC
Labels: bug
